uktrade/lite-hmrc

- mail/enums.py
- mail/libraries/builders.py
- mail/libraries/edifact_validator.py
- mail/libraries/lite_to_edifact_converter.py
- mail/serializers.py
- mail/tasks.py
- mail/tests/files/licence_payload_file
- mail/tests/test_licence_to_edifact.py
- mail/tests/test_send_lite_licence_updates_task.py
Update edifact file generation as per specification
Following things are fixed as per Spec DES236,
- include reset run number indicator in header
- Update the licence types as required by spec
- include country line according to licence type
- Fix licence line data as per spec
- pad quantity unit with leading zeros to make it 3 char wide string
Update tests
Add validator to ensure file content is as per specification.
Helper functions check each line for expected fields and returns list of errors.
> LTD-776: Edifact file generation remediation changes

- mail/libraries/edifact_validator.py
- mail/libraries/lite_to_edifact_converter.py
- mail/tests/files/licence_payload_file
- mail/tests/test_licence_to_edifact.py
The length of each address line has a limit as per specification. This PR updates the generation code to validate for these limits and report errors accordingly.
The foreign trader address is currently captured as a single text field and we cannot control the format in which the user provides this address. To stick to the limits as per spec this address is split into chunks and the file is generated accordingly.
Updated tests and added new ones to test the new functionality.
> LTD-787: Edifact address line fixes

- mail/libraries/builders.py
- mail/tests/test_data_processors.py
Current datetime is used as date
> LTD-787: Add missing datetime attribute while building EmailMessageDto

- mail/libraries/helpers.py
- mail/tests/test_select_email_for_sending.py
We should only send licenceData mail to HMRC after we receive the reply for the previous mail.
If we are waiting for a reply we shouldn't send another mail.
Currently because of this bug the service is sending mail even when we are waiting for reply.
We can however send usageData mails to SPIRE so they are not prevented.
> LTD-1082: Don't send another licenceData mail if waiting for a reply

- mail/libraries/helpers.py
- mail/libraries/routing_controller.py
- mail/serializers.py
- mail/tests/test_select_email_for_sending.py
During every polling session export the queue status to Sentry so that we
can check the status without logging into the mailboxes.
> LTD-1088: Expose Mail queue status to Sentry periodically

- mail/libraries/usage_data_decomposition.py
- mail/tests/test_send_licence_usage_figures_to_lite_api.py
Because this is an additional transaction that is sent when all the
allowed quantity of all items on that licence are used. Sending it
again results in double counting of the recorded usage.
The completion date is empty for the actual licenceUsage transaction
which is not disturbed.
> LTD-1480: Don't send licenceUsage transactions with completion date to LITE-API

- conf/authentication.py
This was incorrectly returning the class whereas a user object is expected
> Return anonymous user object from hawk auth

- mail/libraries/helpers.py
- mail/models.py
- mail/tasks.py
This is due to the fact that sentry doesn't display the stack trace when just using stack_info but will always show a trace (even without an exception) if you set exc_info
> Update logging calls from stack_info to exc_info

- mail/management/commands/resend_email.py
These logging calls had a mix of f-strings and format calls, which "works"
but does not do what was intended.
>>> f"Status {0}".format("fail")
'Status 0'
But for Python's logging module, one should use positional arguments, not
string formatting (f-strings or other flavours). This way the logging
module can delay string formatting until it is needed (or even never if
the logging level means the message is skipped). Also the logging module
will swallow unicode encode/decode errors when formatting strings, which
allows the program to continue.
> ICMSLST-1464 Fix broken use of logging

- mail/libraries/lite_to_edifact_converter.py
HMRC only allows 2-char country codes and territory codes are longer
than that. If any country is a territory then we strip the territory
code and use the country for that territory. This was missed for
foreign trader address
> Strip territory code from Foreign trader address

- mail/libraries/data_processors.py
- mail/tests/test_retreive_and_process_multiple_emails.py
Stops attempting to create/update mail message if an instance isn't returned for licence reply type
> Stop dummy email from being created

- conf/views.py
- mail/apps.py
- mail/requests.py
- mail/servers.py
- mail/tasks.py
- mail/tests/test_data_processors.py
- mail/tests/test_end_to_end.py
- mail/tests/test_helpers.py
- mail/tests/test_retreive_and_process_multiple_emails.py
- mail/tests/test_send_licence_usage_figures_to_lite_api.py
- mail/tests/test_send_lite_licence_updates_task.py
Instead of import settings from conf.settings, we can use Django's settings
feature which will proxy things from the DJANGO_SETTINGS_MODULE module.
This pattern allows us to override settings in tests, and to point at a
different DJANGO_SETTINGS_MODULE without having to change the imports.
I also updated logging calls in those files that were updated, using
positional arguments instead of string formatting.
> ICMSLST-1465 Use Django's django.conf.settings module

- mail/enums.py
- mail/libraries/helpers.py
- mail/libraries/usage_data_decomposition.py
- mail/tasks.py
- mail/tests/test_helpers.py
- mail/tests/test_usage_data_decompostion.py
HMRC sends us usage data when a licence is used but when the licence is
completed i.e., all the allowed quantity of all products on that licence
are used then we get another usage data transaction with licence status
as cancelled. Currently we skip these transactions hence the licence count
in the payload comes up as 0 but we are trying to report this to LITE.
Since the licences are empty, LITE considers this as an error and throws
an exception. This is not an error and we can skip reporting in this case.
> Skip reporting usage data when there are no licences

- mail/models.py
- mail/tests/test_combining_responses.py
- mail/tests/test_data_processors.py
- mail/tests/test_select_email_for_sending.py
- mail/tests/test_send_licence_usage_figures_to_lite_api.py
- mail/tests/test_send_lite_licence_updates_task.py
- mail/tests/test_usage_data_decompostion.py
There is no valid case where these fields can be empty so check explicitly and fail if either of these fields are empty.
Update tests.
> LTD-1921: Make edi_filename and edi_data non-nullable

- mail/libraries/chiefprotocol.py
- mail/libraries/lite_to_edifact_converter.py
- mail/tests/libraries/test_chiefprotocol.py
Every line in a CHIEF message starts with the line number, and "end" lines
also have a count of the number of lines since the opening transaction line
(named `distance` in this code change). Moving the logic for line numbering
to the end simplifies the code.
Longer term we should break the logic in `licences_to_edifact(..)` into
smaller pieces, and add flexibility for sending with ILBDOTI (the ICMS
system) and for import licence requests (not just `usage_code = "E"`).
> ICMSLST-1423 Refactor line number logic in CHIEF message builder

- mail/tasks.py
When send_licence_data_to_hmrc() task runs it checks to see if there is an update
in progress. An update can be either we are waiting for a reply or the next email
is about to be processed (eg new email just got created and check_inbox task about
to process it, in this case it will be in pending state).
Since we have to wait till we completely process an email (i.e, reply_sent state)
we should skip this update when there is an update in progress, this gets picked
up in the next polling cycle.
Currently we are logging an error if an update in progress. This is not an error
and it unnecessarily adds noise to the alerts hence remove this.
> LTD: Remove unnecessary mail is pending error as it is not an error

- .pre-commit-config.yaml
Click version 8.1.0 was released recently and it changed some of the
internals. This caused a new clean install of the PII checker tool
to fail with an ImportError exception in a transitive dependency.
For now we can pin the dependency to an older version.
Black released a new version that fixes the use of internals.
> Fix the PII checker and Black failing pre-commits

- mail/libraries/chiefprotocol.py
- mail/libraries/lite_to_edifact_converter.py
- mail/tests/libraries/test_chiefprotocol.py
Instead of making SQL queries, use the actual count of "licence"
transactions that are present in a CHIEF message (which is what
that trailing count is supposed to be).
The advantage of this is we can untangle some of the database
logic from building the actual CHIEF message.
> ICMSLST-1486 Count licences using the CHIEF message

- mail/libraries/lite_to_edifact_converter.py
Including the error text makes it easier to understand what the problem
is when a test breaks with an EdifactValidationError exception. The test
runner prints the exception message, instead of just the exception name.
> ICMSLST-1541 Use the error text for EdifactValidationError's message

- mail/libraries/lite_to_edifact_converter.py
- mail/tests/test_licence_to_edifact.py
We have changed the way the Application reference and hence the licence reference
numbers are generated but didn't update lite-hmrc to consider the new naming
scheme because of this when sending licence details with these new names then
the helper function is not able to generate the reference correctly.
> LTD-2187: Update licence reference extraction to consider new naming scheme

- mail/libraries/chiefprotocol.py
- mail/libraries/chieftypes.py
- mail/libraries/lite_to_edifact_converter.py
- mail/tests/libraries/test_chiefprotocol.py
- mail/tests/test_licence_to_edifact.py
This uses dataclasses to define the line structure, because they support
inheriting field declarations whereas collections.namedtuple does not.
Dataclasses also allow using keyword arguments with the constructor.
The big improvement is we can have a little bit more self-documenting
code with names for the fields, instead of items in tuples with an
order that seems arbitrary but is very significant.
In CHIEF syntax every line starts with the line number and record type,
but for our use it is very useful to leave the line number unknown
until we construct the final message. But if you have one field in a
dataclass as optional, then all fields that follow must also be optional.
> ICMSLST-1541 Add types for CHIEF message lines

- Procfile
- gunicorn.conf.py
Instead of Django's development server, use gunicorn. Default behaviour
reads a configuration from gunicorn.conf.py and binds to 0.0.0.0:$PORT
when $PORT is defined in the environment.
The config overrides the `Server` response header to hide gunicorn's
signature. This is silly, but part of a belt-and-braces approach to
security. However the header is then reset by another proxy. If we ever
deploy the app with a proxy that respects the app `Server` header, it
would show the customised, obscured signature.
> ICMSLST-1537 Use gunicorn for serving in production

- .circleci/config.yml
The pipeline tests failed with "Directory (/home/circleci/lite-hmrc) you are
trying to checkout to is not empty and not a git repository". And it turns
out there's a /home/circleci/lite-hmrc/jq-1.5 directory in there. But we
don't even use jq!
> Fix CI pipeline failures

- mail/serializers.py
- mail/tests/test_serializers.py
- mail/views.py
Move the logic for validating request data from the "/mail/update/" view
handler to the Django Rest Framework serializer class. Because some of
the fields are only required depending on the value of the "type" field,
the serializer fields are declared as optional, and then made required
(if necessary).
> ICMSLST-1530 Use DRF serializers for validating API requests

- mail/enums.py
- mail/libraries/helpers.py
- mail/tests/test_enums.py
- mail/tests/test_helpers.py
Django version 3.x added the choice types for use as enums, so I backported
that implementation and used it for the enum things.
> ICMSLST-1547 Backport Django's Choices/enum type for use with enums

- conf/authentication.py
- conf/views.py
- mail/libraries/builders.py
- mail/libraries/data_converters.py
- mail/libraries/data_processors.py
- mail/libraries/helpers.py
- mail/libraries/lite_to_edifact_converter.py
- mail/libraries/mailbox_service.py
- mail/libraries/routing_controller.py
- mail/management/commands/resend_email.py
- mail/requests.py
- mail/tasks.py
- mail/tests/libraries/client.py
- mail/tests/test_data_processors.py
- mock_hmrc/data_processors.py
The stdlib's logging library is intended to be used with positional arguments,
so that a call that doesn't emit a message can skip formatting.
There were also some totally useless logging calls that have been removed.
>     ICMSLST-1570 Use positional arguments to logging calls

- Pipfile
- Pipfile.lock
This fixes the "bash: gunicorn: command not found" error at startup, which
happened cos I changed the entry point for Cloud Foundry as part of changes
in ICMSLST-1537. Like a genius.
> ICMSLST-1597 Add gunicorn to Python dependencies

- mail/enums.py
- mail/libraries/lite_to_edifact_converter.py
- mail/serializers.py
- mail/tests/test_enums.py
- mail/tests/test_helpers.py
- mail/tests/test_serializers.py
The CHIEF message serializer requires certain fields have certain values,
but the API was not enforcing that.
- goods/unit must be one of the known values.
- goods/id must be a UUID value.
> ICMSLST-1627 Catch invalid licence data

- mail/libraries/helpers.py
Only log an error in sentry when the queue status is not healthy.
> Update queue status sentry logging.

- README.md
- conf/authentication.py
- conf/settings.py
- conf/tests/test_authentication.py
- local_settings.sample
- mail/requests.py
- mail/views.py
Changes:
- Return correct exception when authentication fails for any reason
- Add authentication classes to app endpoints (even if they are only used in testing)
- Add local_settings sample to reduce logging output (remove json formatter).
> Fix hawk authentication

- mail/enums.py
- mail/icms_serializers.py
- mail/libraries/edifact_validator.py
- mail/libraries/lite_to_edifact_converter.py
- mail/tests/files/icms/icms_chief_licence_data_file_sanction
- mail/tests/test_builders.py
- mail/tests/test_edifact_validator.py
- mail/tests/test_end_to_end.py
- mail/tests/test_serializers.py
- mail/views.py
Changes:
- Update LicenceDataIngestView to support SAN licences.
- Add serializer for SAN licences.
- Update ICMS edifact converter to support SAN licences.
- Add enum to define CHIEF controlled by values.
- Add enum to define CHIEF quantity code values.
> ICMSLST-1661 Add Sanction licence data serializer and edifact converter.

- mail/auth.py
- mail/libraries/routing_controller.py
- mail/servers.py
- mail/tests/test_auth.py
- mail/tests/test_mail_service.py
This change is in preparation for when we add OAuth authentication, this separates out the concerns for authenticating the connection and allows us to swap out authentication on a case by case basis if necessary
> Separate out authentication from mail server

- mail/libraries/routing_controller.py
- mail/servers.py
- mail/tests/test_dtos.py
- mail/tests/test_mail_service.py
- mail/tests/test_resend_email.py
- mail/tests/test_select_email_for_sending.py
The user is now a property on the MailServer, as it was before, but provided by the auth object within
This also expands the tests for getting mail messages from the server which was failing due to the original change in the MailServer API
> Reverts back to previous API for user on MailServer

- manifest.yml
When deploying the latest changes for https://github.com/uktrade/lite-hmrc/pull/158 there was a failure when installing the new requirements (sub-dependencies from `msal`, more specifically `cryptography`).
Updating the buildpack has rectified the issues with installing the dependencies.
> Upgrade python buildpack

- mail/libraries/routing_controller.py
The logging message was outputting an entire list of object and as they were named tuples this was including all data for these objects
In this case one of the fields was the attachment data of the emails and this was causing systems that ingest our logs to error due to the size of the logging record
> Remove logging of full EmailMessageDTO list

- mail/views.py
We have a licence that appears to be failing to be created, however we respond with a 400 and the sender doesn't seem to throw any logs to indicate when this has happened. We also don't get the full response back in our logs when we send this back so we don't really know what's causing this problem.
This adds logging so that we're aware of any failures when creating licence data.
> Add logging for failures to ingest licence data

- .coveragerc
- Makefile
- conf/middleware.py
- conf/settings.py
- fake_hmrc
- mail/admin.py
- mail/chief/licence_reply/processor.py
- mail/chief/licence_reply/types.py
- mail/icms/tasks.py
- mail/management/commands/dev_fake_licence_reply.py
- mail/management/commands/dev_process_licence_payload.py
- mail/management/commands/dev_send_licence_data_to_icms.py
- mail/models.py
- mail/tests/icms/test_tasks.py
- mail/tests/management/commands/test_dev_fake_licence_reply.py
- mail/tests/test_models.py
Changes:
- Refactor Chief licence reply types to have a "record_type" class var.
- Add dev command to call send_licence_data_to_hmrc task.
- Add dev command to fake a licenceReply file.
- Add dev command to call send_licence_data_to_icms task.
- Update LicenceData django admin page.
- Add comment explaining the workaround added to HawkSigningMiddleware.
- ICMSLST-1765 Fix send_licence_data_to_icms url and payload.
> ICMSLST-1786 Add commands to fake a HMRC response for end to end testing

- mail/libraries/lite_to_edifact_converter.py
- mail/tests/test_end_to_end.py
- mail/tests/test_licence_to_edifact.py
Initial fix was to also sanitise  the trade address key under [“organisation”] however this fix failed since more than 1 line was going over the 35 charter limit. Since a trader address is split over 5 lines. We have now created a new function which combines the 5 lines and then splits into 35 chars this has a couple of implications :
Trader address format gets changes 
We truncate if we exceed 5 lines
For the later we log in sentry this is the safe fix for now . Long term we should restrict UI from going over.
> LTD-3148-fix-trader-address-multiline 

- conf/settings.py
- conf/tests/test_healthcheck.py
- conf/views.py
This is to add an additional health check when we get payload objects packing up. This can happen when either tasks aren't running or we have a failure. 
Also I have removed the rejected mail responses health check since we don't have an action for these anyway and it doesn't black the Q.
>  LTD-3198-Queue-healthcheck 

- mail/enums.py
- mail/tests/test_enums.py
This is a fix for an error observed in Sentry when creating license data from lite, as a good has `MIR` as the unit in the request body from lite-api, and this is not supported by the lite-hmrc lite good serializer. This changes the UnitMapping to include the `MIR` unit with the appropriate code as in the UK Trade Tariff list (https://www.gov.uk/government/publications/uk-trade-tariff-quantity-codes/uk-trade-tariff-quantity-codes)
> Add MIR to UnitMapping for lite serializer

- .bandit
- .circleci/config.yml
- Pipfile
- Pipfile.lock
- bandit.yaml
bandit(v1.6.2) requires Gitpython(v3.1.32) which has below vulnerability, https://github.com/uktrade/lite-hmrc/security/dependabot/27
Upgraded bandit to 1.6.3 which uses a Gitpython(v3.1.34)
> LTD-4083: Upgrade Gitpython to address a security issue flagged by dependabot

- manifest.yml
This is currently the implicit version but once we upgrade the stack version these change becomes "sticky" and means that even if we try to rollback we can still be stuck with this new version, if this is set explicitly then if we need to rollback it will rollback to this specific version
> This explicitly sets the version for the cf stack in preparation for the cflinuxfs4 upgrade

- manifest.yml
This explicitly sets the version for the cf stack in preparation for the cflinuxfs4 upgrade.
This is currently the implicit version but once we upgrade the stack version these change becomes "sticky" and means that even if we try to rollback we can still be stuck with this new version, if this is set explicitly then if we need to rollback it will rollback to this specific version.
> Ltd 4311 cflinuxfs4

- conf/celery.py
- conf/settings.py
Add `core` explicitly to celery config so that the debug celery tasks contained within are properly registered.
> Ensure debug celery tasks are properly registered

- mail/celery_tasks.py
- mail/models.py
- mail/tasks.py
- mail/test_celery_task.py
- mail/tests/conftest.py
- mail/tests/test_celery_task.py
- mail/tests/test_models.py
- mail/tests/test_tasks.py
Replaced rejected mail with a celery task and implemeted celery into the task which previously was running without background_tasks, which I believe was an oversight
> Ltd-4583: Migrate the task that notifies rejected licences to use Celery

- conf/settings.py
- healthcheck/apps.py
- healthcheck/checks.py
a bit of cleaning up since few things were removed when merged.
> LTD-4645-healthcheck-app-readd

- healthcheck/checks.py
- healthcheck/tests/test_checks.py
This change re-instates the separation of critical/non-critical health checks.  Non-critical health checks will still report an error through to sentry, but will not cause our pingdom checks to alert.  This will reduce alerting spam for the team.
> [LTD-4684] Ensure non critical healthchecks do not result in a failed health check response

- Makefile
- Procfile
- README.md
This is a management command in background_task which is used to start the tasks. We have completely removed background_tasks and switched to celery so this are no longer required.
> LTD-4630: Remove references to process_tasks management command

- conf/celery.py
- conf/settings.py
- mail/celery_tasks.py
- mail/enums.py
- mail/libraries/builders.py
- mail/libraries/routing_controller.py
- mail/tests/test_celery_task.py
- mail/tests/test_end_to_end.py
- mail/tests/test_licence_to_edifact.py
- mail/tests/test_resend_email.py
- mail/tests/test_select_email_for_sending.py
- mail/tests/test_send_lite_licence_updates_task.py
We use SMTP to send emails. As we process messages we also have a requirement to send emails from multiple tasks, because of this we may open multiple SMTP connections concurrently. This results in error if the number of concurrent connections exceed maximum allowed value.
To manage this reliably we are restricting access to this shared resource using a lock. This is achieved by deferring all email sending functionality to a dedicated task.
Before sending email it first tries to acquire a lock.
- If there are no active connections then it acquires lock and sends email.
In some cases we need to update state which is handled in subtasks linked to the parent task.
- If there is active connection (lock acquisition fails) then it raises an exception to trigger an automatic retry.
If all …
> LTD-4652: Manage concurrent SMTP connections using a lock

- mail/enums.py
- mail/tests/files/licence_payload_file
- mail/tests/test_end_to_end.py
- mail/tests/test_enums.py
- mail/tests/test_licence_to_edifact.py
Ensure that we handle translating lite-api's `MIM` unit to chief's unit integer for milligrams.
> [LTD-5022] Support milligrams unit for ingested good data

- .circleci/config.yml
- .pre-commit-config.yaml
- pyproject.toml
Adds the ruff unused import check to pre-commit and CI following the pattern established in lite-frontend, lite-api, lite-routing.
> Add ruff unused import check to pre-commit and CI

- .circleci/config.yml
- Dockerfile
- Pipfile
- Pipfile.lock
- circleci.Dockerfile
Python3.9 upgrade and add typing-extensions package to ensure compatibility.
This has been deployed on the uat environment and tested manually.  Results below.
Manual test case scenarios carried out using `resend_edi_data_email.py` management command:
- EDI data email sent from Spire and ingested by Lite HMRC system with correct db information (PASS)
- EDI data email sent on from Lite HMRC on to HMRC mailbox (PASS)
- LITE API call simulated and Email sent from Lite HMRC to HMRC mailbox (PASS)
Other manual testing:
- Health check viewed (PASS)
- Checked mailbox connections with `mail/management/commands/check_mailserver_connections.py` managment command (PASS)
> LTD-5128 Python3.9 upgrade

- .circleci/config.yml
This removes us using the external codecov tool, which for some reason was no longer working as expected, with the same toolset that we use on our other repos.
> Use custom code coverage checker

- mail/enums.py
- mail/tests/files/licence_payload_file
- mail/tests/test_end_to_end.py
- mail/tests/test_enums.py
- mail/tests/test_licence_to_edifact.py
This updates the units of measurement codes to match the lists published by HMRC. More context is given in the ticket.
[LTD-5293](https://uktrade.atlassian.net/browse/LTD-5293)
[LTD-5293]: https://uktrade.atlassian.net/browse/LTD-5293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update UnitMapping codes to match HMRC list

- mail/libraries/helpers.py
- mail/tests/libraries/test_helpers.py
Since the last lite-hmrc release, we have been getting fairly regular `LookupError` exceptions logged to sentry.  It's likely that is due to a backward incompatibility as we bumped sentry-sdk's major version.
This updates the call that creates a new sentry scope as per docs for upgrading from 1.x to 2.x; https://docs.sentry.io/platforms/python/migration/1.x-to-2.x#scope-configuring
> [LTD-5327] Update sentry scope pushing call after major version bump

- mail/auth.py
- mail/tests/test_auth.py
Throw an error with additional logging when getting an access token fails.
> Add logging and exception for access token failure

- conf/authentication.py
- conf/tests/test_authentication.py
On DBT Platform there is a URL mismatch between the HMRC and API apps which causes a hawk auth failure on the HMRC side.  There is an unusual piece of code which replaces http with https which causes the Message Authentication Code to change which appears to have been a hack to get the auth to work correctly on gov paas.
Once this is removed the systems communicate normally but this change must be backwards compatible with Gov Paas.
Deployed on dev data environment for testing and some short testing notes are included on the ticket
[LTD-5751](https://uktrade.atlassian.net/browse/LTD-5751)
[LTD-5751]: https://uktrade.atlassian.net/browse/LTD-5751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix communication between LITE API and LITE HMRC

- conf/settings.py
Remove adding APM to installed apps when there is no URL set.
This was causing lots of logging errors.
> Only add APM app if env setting is set

- mail/libraries/builders.py
- mail/libraries/edifact_validator.py
- mail/libraries/lite_to_edifact_converter.py
- mail/tests/files/licence_payload_file_special_characters
- mail/tests/test_builders.py
- mail/tests/test_edifact_validator.py
- mail/tests/test_licence_to_edifact.py
**Issue:**
* hmrc requires a length of 35 per address line
* lite-hmrc achieved this using textwrap
* unidecode appended to the character count and we managed to go over
**Things to note:**
I had initially added the unidecode to edifact_validators so that the validator could catch the error and went back and forth with this idea for a little while, in theory because it's decoded now in the sanitizer (lite_to_edifact_converter) it will never hit the sanitizer with special characters present.
I have also added some coverage tests in test_builder so that we cant remove this and accidentally have things pass. 
if we notice any other edge cases we could update the new payload file to include them
[LTD-5853](https://uktrade.atlassian.net/browse/LTD-5853)
[LTD-5853]: …
> LTD-5853 unidecode before textwrapping

- mail/serializers.py
- mail/tests/test_serializers.py
- mail/tests/test_update_licence_endpoint.py
- mail/views.py
This change preserves the exact logic for required fields etc that we had before, it just refactors the code so instead of if-statements we have separate serializers and a mapping between specific licence types and specific serializers.
The tests have also been updated so we are testing specific serializers instead of that generic serializer.
Also added a test for the new NotImplementedError.
[LTD-6174](https://uktrade.atlassian.net/browse/LTD-6174)
[LTD-6174]: https://uktrade.atlassian.net/browse/LTD-6174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update licence data serializers
