mail/dtos.py, mail/services/MailboxService.py, mail/services/helpers.py, mail/views.py
set email message as raw_data in the EmailMessageDto
=> LT-1909 set raw_data in the EmailMessageDto

.circleci/config.yml, .gitignore, Pipfile, Pipfile.lock, docker-compose.yml, mail/libraries/mailbox_service.py, mail/requests.py, mail/tests/test_mail_service.py
BUGFIX: Retrieve messages from pop3 using message_id not index position in LIST of
messages.
=> LTD-566 Email retrieval logic bug

Pipfile, Pipfile.lock, conf/settings.py
Along similar lines as https://github.com/uktrade/lite-api/pull/756
=> Add ECS log formatter

mail/libraries/helpers.py, mail/libraries/routing_controller.py, mail/tests/test_select_email_for_sending.py
Usually we send one mail to HMRC and wait for the reply. Sometimes we get
multiple emails (eg usageData mail along with a licence data or reply)
in the same polling session then we process both of them (serialize and save)
but currently we send only one of them. The status of second one becomes "pending".
If there are no new emails currently we simply return and the pending mail
doesn't get processed. If the pending mail is of type licenceData then we get into
a deadlock situation because the mail is not sent to HMRC and we don't get any
reply. Unless we get a reply (new mail) we don't process these emails (currently).
To fix this we check for any pending mails when there are no unread mails in the inbox.
Please note that even if there are multiple pending mails we only process one of …
=> LTD-1054: Fix sending of pending mails stuck in the queue

README.md, mail/libraries/helpers.py, mail/serializers.py, mail/tests/test_end_to_end.py, mail/urls.py, mail/views.py
Add an endpoint to lite-hmrc that takes a license id and returns back the mail status.
=> Ltd 979 license status query

mail/libraries/mailbox_service.py
degrade unknown emails from error to warning
=> degrade unknown emails from error to warning

mail/libraries/helpers.py, mail/libraries/lite_to_edifact_converter.py, mail/tests/test_helpers.py
stripping territory code while building the data file so as to push licences that come with it
=> stripping territory code while building the data file

mail/libraries/lite_to_edifact_converter.py
Moved the logic for generating message lines for each licence to a separate
function. The function knows nothing about line numbers, so we don't need to
pass that state between each loop iteration.
This also means we can remove the `noqa` that I added in order to silence
the McCabe complexity warning (Prospector's MC0001 error).
Bugs like `trader.get(..).get(..)` have been preserved for now.
=> ICMSLST-1423 Refactor CHIEF message building for multiple licences

Pipfile, Pipfile.lock
- https://pycqa.github.io/isort/CHANGELOG.html
- https://black.readthedocs.io/en/stable/change_log.html
=> ICMSLST-1544 Update isort==5.10.1, black==22.3.0

mail/libraries/chieftypes.py
These comments are adapted from the DES 235 and DES 236 specifications.
=> ICMSLST-1549 More info on the meaning of CHIEF message fields

mail/enums.py, mail/libraries/helpers.py, mail/tests/libraries/client.py, mail/tests/test_helpers.py, mail/tests/test_resend_email.py, mail/views.py
- Tests that were never run, and which fail anyway.
- Unused API views.
- Unused helper methods on the enum-like classes.
- Unused base64 helpers.
=> ICMSLST-1545 Remove unused code

mail/libraries/lite_to_edifact_converter.py, mail/tests/test_licence_to_edifact.py
=> Revert "LTD-2187: Update licence reference extraction to consider new naming scheme"

mail/libraries/lite_to_edifact_converter.py, mail/tests/test_licence_to_edifact.py
=> Revert "Revert "LTD-2187: Update licence reference extraction to consider new naming scheme""

Dockerfile, Makefile, README.md
Changes:
- Update README.md to document how to setup and test the application
- Update Dockerfile to be able to run make commands in app container
- Add migrate & createsuperuser make commands
=> Improve developer onboarding.

.circleci/config.yml, Pipfile, Pipfile.lock, pytest.ini
git push --set-upstream origin setup-pytest
=> Setup pytest and add code coverage

mail/admin.py, mail/icms_serializers.py, mail/libraries/lite_to_edifact_converter.py, mail/tests/test_serializers.py, mail/views.py
Changes:
- Add ICMS serializer for FA-OIL application.
- Add models to admin interface for debugging.
- Fix optional date values throwing exceptions.
=> ICMSLST-1654 Add ICMS serializer for FA-OIL application.

.coveragerc, Pipfile, Pipfile.lock, README.md, mail/auth.py, mail/tests/test_auth.py, mail/tests/test_mail_service.py, pii-secret-exclude.txt
This adds an authentication class for OAuth based authentication for pop3 connections.
At this point in time this is unused but is laying the ground work for the switch to OAuth.
=> Add modern authentication auth class

Makefile, README.md, mail/apps.py
Other changes:
- Document task queue system
=> Update task config to run tasks depending on source system.

Pipfile, Pipfile.lock
… Python.h: No such file or directory` errors on deployment
=> Downgrade setuptools to stop deployment failures

circleci.Dockerfile, conf/tests/test_healthcheck.py, conf/views.py, mail/auth.py, mail/management/commands/check_mailserver_connections.py
- Updates the management command to check against all mailboxes regardless of whether one fails or not.
- Adds additional logging calls for authentication calls
- Adds auth checks to healthcheck
=> Mailbox connection

.circleci/config.yml
Add test jobs to run against postgres13
[LTD-4955](https://uktrade.atlassian.net/browse/LTD-4955)
[LTD-4955]: https://uktrade.atlassian.net/browse/LTD-4955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-4955 Add test jobs to run against postgres13

.InstallPackages, .copilot/config.yml, Procfile
Add additional configurations to allow this codebase to run as a scheduled task on DBT Platform.
=> LTD-5686-DBT-HMRC-Config

conf/authentication.py, conf/celery.py, conf/settings.py, conf/tests/test_authentication.py
https://uktrade.atlassian.net/browse/LTD-5753
post migration clean-up tasks 
Tested on DBT-Platform Dev3 environment. Processed a licence and can see payloads using this build.
=> LTD-5753--dbt-platform-migration-post-clean-up

.copilot/phases/pre_build.sh
Update the pre build step to match the standard way of pulling submodules
=> Update codestar connection step
